name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 2.3.0
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  url_launcher: ^6.3.0
  emoji_picker_flutter: ^3.0.0
  any_link_preview: ^3.0.2
  image_picker: '>=0.8.9 <2.0.0'
  audio_waveforms: ^1.0.5
  # For formatting time locale in message receipts
  timeago: ^3.7.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

