name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 0.0.3
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  grouped_list: ^5.1.2
  intl: ^0.17.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.4
  emoji_picker_flutter: ^1.3.0
  http: ^0.13.4
  html: ^0.15.0
  any_link_preview: ^2.0.9
  progress_indicators: ^1.0.0
  image_picker: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

